backend:
  name: github
  repo: freecodecamp-greenville/fcc-greenville-www
  branch: master
media_folder: "images/uploads"
collections:
  -
    name: "pages"
    label: "Pages"
    files:
      -
        name: "home"
        label: "Home"
        file: "index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/default.njk"}
          - {label: "Body", name: "body", widget: "markdown"}
